export const WMS_PROVIDERS = [
  {
    id: "yunwms_ru",
    name: "俄罗斯 YunWMS",
    docUrl: "https://fsdd.yunwms.com/api-doc/index.php",
    region: "俄罗斯",
    authFields: ["baseUrl", "appKey", "appToken", "warehouseCode"],
    notes: "同一套系统可新增多个俄罗斯仓库授权，接口域名通常固定，仓库编码区分库存范围。",
  },
  {
    id: "sea_wms",
    name: "斗仓 / 神牛 SEA WMS",
    docUrl: "https://s.apifox.cn/422721aa-3e4e-48b3-89dd-eae8192f22ac/doc-4253934",
    region: "越南 / 马来西亚 / 印尼",
    authFields: ["baseUrl", "clientId", "clientSecret", "warehouseCode", "warehouseId"],
    notes: "同一套接口模型下，不同国家和仓库可能使用不同接口地址，需要按仓库保存 baseUrl。",
  },
];

export const WAREHOUSE_CONNECTIONS = [
  {
    id: "ru-moscow-1",
    name: "莫斯科一仓",
    country: "俄罗斯",
    providerId: "yunwms_ru",
    providerName: "俄罗斯 YunWMS",
    baseUrl: "https://fsdd.yunwms.com",
    warehouseCode: "RU-MOW-01",
    status: "待授权",
    lastSyncedAt: "",
    skuMatched: 0,
    syncScope: ["库存同步", "订单出库日报"],
  },
  {
    id: "vn-doucang-a",
    name: "越南斗仓 A",
    country: "越南",
    providerId: "sea_wms",
    providerName: "斗仓 / 神牛 SEA WMS",
    baseUrl: "待配置",
    warehouseCode: "VN-DC-A",
    status: "待授权",
    lastSyncedAt: "",
    skuMatched: 0,
    syncScope: ["库存同步", "订单出库日报", "动销监控"],
  },
  {
    id: "my-shenniu-1",
    name: "马来神牛一仓",
    country: "马来西亚",
    providerId: "sea_wms",
    providerName: "斗仓 / 神牛 SEA WMS",
    baseUrl: "待配置",
    warehouseCode: "MY-SN-01",
    status: "待授权",
    lastSyncedAt: "",
    skuMatched: 0,
    syncScope: ["库存同步", "订单出库日报", "动销监控"],
  },
  {
    id: "id-shenniu-jakarta",
    name: "印尼神牛雅加达仓",
    country: "印尼",
    providerId: "sea_wms",
    providerName: "斗仓 / 神牛 SEA WMS",
    baseUrl: "待配置",
    warehouseCode: "ID-SN-JKT",
    status: "待授权",
    lastSyncedAt: "",
    skuMatched: 0,
    syncScope: ["库存同步", "订单出库日报", "动销监控"],
  },
];
